### ISSUE TITLE
Where is the Build Guide?

### ISSUE THREAD

**Issue by chschmit** [Reiten966/Polyformer#1]
Your website mentions a Build Guide on your GitHub, but I'm not finding it...only the CAD files.

**Comment by FacuM** [comment]
I'm bumping that, where's that build guide? lol

**Comment by milador** [comment]
Excellent work on the BOM file, software,  and CAD files! The guide is missing though as it's mentioned.

**Comment by dbatey** [comment]
Looks like this one can be closed! Thanks for the crazy fast response :)

**Comment by Reiten966** [comment]
build guide was in the discord and now I moved it here. I am working on a written guide as well but that is gonna take a while. A few assembly videos will do for now.
